routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Auth::routes();

Route::get('/', 'FuncionarioController@index')->name('home');

Route::get('/home', 'HomeController@index')->name('admin');
Route::resource('funcionario', 'FuncionarioController');
Route::get('funcionarios/todos', 'FuncionarioController@listaTodos');

Route::group(['middleware' => 'auth:funcionario'], function () {
    Route::get('/meu-estado', 'FuncionarioController@estado')->name('usuario.estado');
    Route::get('/sair', 'FuncionarioController@logout')->name('sair');
    Route::resource('prova', 'ProvaVidaController');
});

Route::group(['middleware' => 'auth:web'], function () {
    Route::get('/estado', 'FuncionarioController@formularioEstado')->name('estado.formulario');
    Route::post('/estado', 'FuncionarioController@pesquisar')->name('funcionario.procurar');
});

Route::prefix('usuario')->group(function () {
    Route::get('/acessar', 'Auth\FuncionarioLoginController@showLoginForm')->name('usuario.acessar');
    Route::post('/login', 'Auth\FuncionarioLoginController@login')->name('usuario.login');

});

app/Funcionario.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class Funcionario extends Authenticatable
{
    use Notifiable;

    protected $guard = 'funcionario';
    protected $primaryKey = 'id';
    public $timestamps = true;
    protected $fillable = [
        'nome',
        'apelido',
        'data_de_nascimento',
        'bi',
        'nuit',
        'telefone',
        'password',
        'is_verdade'
    ];
    protected $table = 'funcionarios';


    protected $hidden = [
        'password', 'remmenber_token'
    ];

    public function isAdmin()
    {
        return false;
    }

    public function provas()
    {
        return $this->hasMany('App\ProvaVida');
    }

    public function prova(){
        return $this->hasOne(ProvasVida::class)->where('ano', date('Y'))->first();
    }
}

app/Http/Controllers/FuncionarioController.php
<?php

namespace App\Http\Controllers;

use App\Funcionario;
use App\Http\Requests\FuncionarioRequest;
use App\ProvasVida;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Twilio\Rest\Client;

class FuncionarioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Auth::guard('funcionario')->user()) {
            return view('home_funcionario');
        } else if (Auth::check() && Auth::user()->isAdmin()) {
            return view('home');
        } else {
            return view('welcome');
        }

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {

        if (Auth::check()) {
            $request->user()->authorizeRoles(['admin']);
            return view("funcionario.create");
        } else {
            return redirect('/');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(FuncionarioRequest $request)
    {
        $request->user()->authorizeRoles(['admin']);

        $funcionario = new Funcionario();
        $funcionario->nome = $request->nome;
        $funcionario->apelido = $request->apelido;
        $funcionario->data_de_nascimento = $request->data_de_nascimento;
        $funcionario->bi = $request->bi;
        $funcionario->nuit = $request->nuit;
        $funcionario->telefone = "+258" . $request->telefone;
        $funcionario->password = Hash::make($request->password);
        $funcionario->save();

        return redirect("funcionarios/todos");
    }

    public function formularioEstado()
    {
        return view('funcionario.marcar_prova');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Funcionario  $funcionario
     * @return \Illuminate\Http\Response
     */
    public function show(Funcionario $funcionario)
    {
        //
    }

    public function pesquisar(Request $request)
    {
        $funcionario = Funcionario::where('nuit', $request->input('nuit'))->first();
        if ($funcionario != null) {
            return redirect('/estado')->with('funcionario', $funcionario);
        } else {
            return redirect('/estado')->with('funcionario', "NULL");
        }

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Funcionario  $funcionario
     * @return \Illuminate\Http\Response
     */
    public function edit(Funcionario $funcionario)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Funcionario  $funcionario
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Funcionario $funcionario)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Funcionario  $funcionario
     * @return \Illuminate\Http\Response
     */
    public function destroy(Funcionario $funcionario)
    {
        //
    }

    public function alterarEstado(Funcionario $funcionario)
    {
        //
    }

    public function logout()
    {
        Auth::guard('funcionario')->logout();
        return redirect('/');
    }

    public function estado()
    {
        if (Auth::guard('funcionario')->user()) {

            $isConfirmed = ProvasVida::where('funcionario_id', Auth::user()->id)
                ->where('ano', date('Y'))->where('is_confirmed', 1)->first();

            $mes = date('m', strtotime(Auth::user()->data_de_nascimento));

            return view('funcionario.estado')->with(['isConfirmed' => $isConfirmed, 'mes' => $mes, 'provas' => ProvasVida::where('funcionario_id', Auth::user()->id)->get()]);
        } else {
            return view('home');
        }

    }

    public function listaTodos()
    {
        // return Role::all();

        $today = date('m');
        $listaDeFuncionariosDoMes = array();
        $funcionarios = Funcionario::paginate(10);
        // return $funcionarios;

        if (!empty($funcionarios)) {
            foreach ($funcionarios as $funcionario) {
                $month = date('m', strtotime($funcionario->data_de_nascimento));
                $isDoMes = $month == $today;
                if ($isDoMes) {
                    array_push($listaDeFuncionariosDoMes, $funcionario);
                }
            }
        }
        return view('funcionario.index', compact('funcionarios'));

    }
}

resources/views/funcionario/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">

                <div class="font-weight-light badge badge-dark text-wrap" style="width: 30%;">
                    {{ Auth::user()->name }}
                </div>
                <div class="card-body">
                    <h3 class="font-weight-normal" style="margin-top: 2%">Registo de funcionário no sistema de notificacao para prova de vida
                    </h3>
                    <hr>
                    <form style="margin-top: 3%" method="POST" action="{{ route('funcionario.store') }}">
                        @csrf
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label class="font-weight-bold" for="nome">Primeiros nomes</label>
                                <input type="text" name="nome" class="form-control @error('nome') is-invalid @enderror"
                                    placeholder="Ex:. Beltrano Cicrano" value="{{ @old("nome") }}" id="nome">
                                @error('nome')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                            <div class="form-group col-md-6">
                                <label class="font-weight-bold" for="apelido">Apelido</label>
                                <input type="text" class="form-control @error('apelido') is-invalid @enderror"
                                    name="apelido" placeholder="Ex:. Fulano" value="{{ @old("apelido") }}"
                                    id=" apelido">

                                @error('apelido')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label class="font-weight-bold" for="bi">Número de Bilhete de identidade</label>
                                <input type="text" class="form-control @error('bi') is-invalid
                                    @enderror" name="bi" id="bi" placeholder="Ex:. 01011111111111B"
                                    value="{{ @old("bi") }}" autocomplete="nope" style="text-transform:uppercase">
                                @error('bi')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                            <div class="form-group col-md-6">
                                <label class="font-weight-bold" for="nuit">Número de Identificação Tributária</label>
                                <input type="number" class="form-control @error('nuit') is-invalid
                                    @enderror" name="nuit" value="{{ @old("nuit") }}" id="nuit"
                                    placeholder="Ex:. 05050500">
                                @error('nuit')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label class="font-weight-bold" for="data_de_nascimento">Data de nascimento</label>
                                <input type="date" name="data_de_nascimento" value="{{ @old("data_de_nascimento") }}"
                                    class="form-control @error('data_de_nascimento')
                                    is-invalid @enderror" id="data_de_nascimento" placeholder="Ex:. 01/01/2020">
                                @error('data_de_nascimento')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror

                            </div>
                            <div class="form-group col-md-6">
                                <label class="font-weight-bold" for="telefone">Contacto telefónio</label>
                                <input type="number" class="form-control @error('telefone') is-invalid @enderror"
                                    name="telefone" id="telefone" value="{{ @old("telefone") }}"
                                    placeholder="Ex:. 840000000">
                                @error('telefone')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="font-weight-bold" for="password">Password</label>
                            <input type="password" autocomplete="new-password"
                                class="form-control @error('password') is-invalid @enderror" name="password"
                                id="password" placeholder="Senha">
                            @error('password')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <div class="form-check">
                                <input class="form-check-input" name="is_verdade" type="checkbox"
                                    value="{{ @old("is_verdade") }}" onclick="isVerdade()" id="is_verdade">
                                <label class="text-monospace form-check-label @error('is_verdade') is-invalid @enderror"
                                    for="is_verdade">
                                    Confirmo que a informação acima é verídica
                                </label>
                                @error('is_verdade')
                                <p class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </p>
                                @enderror
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary col-sm-4 font-weight-normal">Registar no sistema</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection
<script>
    function isVerdade(){
        var checkbox = document.getElementById('is_verdade');
            if (checkbox.checked == true){
                checkbox.value = true
            }else{
                checkbox.value = null
            }
    }
</script>

resources/views/funcionario/estado.blade.php
@extends('layouts.app_funcionario')

@section('content')

<div class="container">

    @include('layouts.flash_messages')

    <div class="row no-gutters" style="margin-top:2%">
        <div class="col-sm-8 col-md-8 mycontent-left" style="border-right: 1px dashed; border-color: #CECECE">

            @if($mes < date('m'))
            <div class="form-group col-md-10">
                <h5 class="font-weight-bold text-secondary">Aguarde pelo mês de {{ date('m', strtotime(Auth::user()->data_de_nascimento)) }} para realizar a prova de vida</h5>

            </div>
            @elseif(!$isConfirmed and $mes == date('m'))
            <form style="margin-top: 3%" method="POST" action="{{ route('prova.store') }}">
                @csrf
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <h4 class="font-weight-bold " for="nome">Confirmar a prova de vida</h4>

                    </div>
                </div>
                <div class="form-group">
                    <div class="form-check">
                        <input class="form-check-input" onclick="isConfirmed()" name="is_confirmed" type="checkbox"
                            id="is_confirmed">
                        <label class="text-monospace form-check-label" for="is_confirmed">
                            Confirmo a minha prova de vida ao ano de {{ now()->year }}
                        </label>
                    </div>
                </div>
                <button type="submit" disabled id="comfirm" class="btn btn-secondary">Confirmar
                    prova de
                    vida</button>
            </form>
            @elseif(!$isConfirmed and $mes > date('m'))
            <div class="form-group col-md-12">
                <h5 class="font-weight-bold text-secondary">Não realizou a prova de vida no mês próprio</h5>

            </div>
            @endif
            <div class="spinner-grow align-self-center" hidden style="width: 3rem; height: 3rem;" id="status"
                role="status">
                <span class="sr-only">Aguarde a confirmação...</span>
            </div>

            {{-- Dados do funcionário  --}}

            <form style="margin-top: 10%; margin-right: 5%" method="POST"
                action="{{ route('funcionario.update', Auth::user()->id) }}">
                @csrf
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <h5 class="font-weight-light text-secondary" for="nome">Seu número de telefone já não é o mesmo?
                        </h5>

                    </div>
                </div>
                <div class="form-group">
                    <label class="font-weight-bold" for="telefone">Contacto telefónio</label>
                <input disabled type="number" value="{{ substr(Auth::user()->telefone, 4, 13)  }}" class="form-control" name="telefone" id="telefone">
                </div>

                <div class="btn-group" role="group" aria-label="First group">
                    <button type="button" onclick="visibleCell()" class="btn btn-dark">Editar contacto</button>
                    <button type="button" class="btn btn-success">Actualizar contacto telefónico</button>
                </div>
            </form>

        </div>
        <div class="col-6 col-md-4 mycontent-right" style="padding-left: 1%; margin-top: 5%">

            <h5 class="font-weight-bold text-secondary" style="margin-bottom: 5%">Lista de provas de vida</h5>

            @if($mes <= date('m') and !$isConfirmed)
            <div class="card border-danger mb-3" style="max-width: 18rem;">
                <div class="card-header text-danger">Confirmada</div>
                <div class="card-body text-secondary">
                    <h5 class="card-title text-dark font-weight-bold">Prova de vida de {{ date('Y') }}</h5>
                    <p class="card-text">Precisa confirmar a prova de vida no mês de
                        {{ date('m', strtotime(Auth::user()->data_de_nascimento))  }} de {{ date('Y') }}</p>
                </div>
            </div>
            @endif

            @foreach ($provas as $prova)

            <div class="card border-danger mb-3" style="max-width: 18rem;">
                <div class="card-header text-danger">{{ $prova->is_confirmed? 'Confirmada' : 'Não confirmada'  }}</div>
                <div class="card-body text-secondary">
                    <h5 class="card-title text-dark font-weight-bold">Prova de vida de {{ $prova->ano }}</h5>
                    <p class="card-text">Registou a confirmação da sua prova de vida em
                        <span class="font-weight-bold">{{ date('d - m - yy', strtotime($prova->created_at)) }}</span> às
                        {{ date('H:i:s', strtotime($prova->created_at)) }}</p>
                </div>
            </div>

            @endforeach
        </div>
    </div>
</div>
@endsection
<script>
    var click = document.getElementById('comfirm');
    var status = document.getElementById('status');
    var checkbox = document.getElementById('is_confirmed');
    function isConfirmed(){

        var click = document.getElementById('comfirm');
            var status = document.getElementById('status');
            var checkbox = document.getElementById('is_confirmed');
            if (checkbox.checked == true){
                checkbox.value = true
                click.disabled=false
                click.className = "btn btn-primary";
            }else{
                checkbox.value = false
                click.disabled=true
                click.className = "btn btn-secondary";
            }
    }

    function confirm(){
        var click = document.getElementById('comfirm');
        var status = document.getElementById('status');
        click.disabled=true
        status.hidden = false

        var check = document.getElementById('is_confirmed');
        var isConfirmed = check.value;
        $.ajax({
        /* the route pointing to the post function */
        url: '/prova',
        method: 'POST',
        /* send the csrf-token and the input to the controller */
        type: "POST",
        data: {"_token": "{{ csrf_token() }}", is_confirmed: isConfirmed},
        dataType: 'text',
        /* remind that 'data' is the response of the AjaxController */
            success: function (response) {
                status.hidden = true
                console.log(response)
            },
            error: function(XMLHttpRequest, textStatus, errorThrown){
                status.hidden = true
                console.log("erro  "+textStatus);
            }
        });
    }

    function visibleCell() {
        var telefone = document.getElementById('telefone');
        telefone.disabled = false;
    }
</script>

resources/views/funcionario/index.blade.php
@extends('layouts.app')
@section('content')

<h3 style="margin-left: 5% !important; margin-bottom: 2% !important;" class="h4">Lista de funcionarios registados</h3>
<div style="margin-right: 5% !important; margin-left: 5% !important">

<table id="example" class="table table-striped table-bordered mx-auto">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Nome</th>
            <th scope="col">Apelido</th>
            <th scope="col">Número de BI</th>
            <th scope="col">Nuit</th>
            <th scope="col">Data de nascimento</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($funcionarios as $funcionario)
        <tr>
            <td>{{ $funcionario->nome }}</td>
            <td>{{ $funcionario->apelido }}</td>
            <td>{{ $funcionario->bi }}</td>
            <td>{{ $funcionario->nuit }}</td>
            <td>{{ date('d-m-Y', strtotime($funcionario->data_de_nascimento)) }}</td>
        </tr>
        @endforeach
    </tbody>

</table>

{!! $funcionarios->links() !!}
</div>
<script type="text/javascript" defer>
    $(document).ready(function () {
        $('#example').DataTable({
        responsive: true,
        "language": {
        searchPlaceholder: "Pesquisar ...",
        url: 'https://cdn.datatables.net/plug-ins/1.10.20/i18n/Portuguese.json'
        }
        });
        });
</script>
@endsection

resources/views/funcionario/marcar_prova.blade.php
@extends('layouts.app')

@section('content')

<div class="container">

    @include('layouts.flash_messages')

    <div class="row no-gutters" style="margin-top:2%">
        <div class="col-sm-8 col-md-8 mycontent-left" style="border-right: 1px dashed; border-color: #CECECE">

            <form style="margin-top: 3%" method="POST" action="{{ route('funcionario.procurar') }}">
                @csrf
                <div class="form-row">
                    <div class="form-group col-md-8">
                        <h5 class="font-weight-bold " for="nome">Pesquisar pelo Número de Identificação Tributária</h5>

                    </div>
                </div>
                <div class="form-group col-md-10">
                    <input class="form-control" placeholder="Número de Identificação Tributária" name="nuit"
                        type="number" id="nuit">
                    {{-- <label class="text-monospace form-check-label" for="nuit">
                            Confirmo a minha prova de vida ao ano de {{ now()->year }}
                    </label> --}}
                    <br>
                    <button type="submit" class="btn btn-info text-white font-weight-bold col-md-4">Pesquisar</button>
                </div>

            </form>

        </div>

        @if (session('funcionario'))

        @if(session('funcionario') != "NULL" )
        <div class="col-8 col-md-4 mycontent-right" style="padding-left: 1%; margin-top: 5%">
            <div class="card border-danger mb-3">
                <div class="card-header text-success">Prova de vida em dia</div>
                <div class="card-body text-secondary">
                    <h5 class="card-title text-dark font-weight-bold">{{ session('funcionario')->nome}}</h5>
                    <p class="card-text">Número de BI: <strong>{{ session('funcionario')->bi }}</strong>
                    </p>
                </div>
            </div>


            <hr>
        @if(date('m', strtotime(session('funcionario')->data_de_nascimento)) > date('m'))
            <form style="margin-top: 3%" method="POST" action="{{ route('prova.store') }}">
                @csrf
                <div class="form-row">
                    <div class="form-group col-md-10">
                        <h5 class="font-weight-bold " for="nome">Confirmar a prova de vida</h5>

                    </div>
                </div>
                <div class="form-group">
                    <div class="form-check">
                        <input class="form-check-input" onclick="isConfirmed()" name="is_confirmed" type="checkbox"
                            id="is_confirmed">
                        <label class="text-monospace text-small form-check-label" for="is_confirmed">
                            Confirmar a prova de vida ao ano de {{ now()->year }}
                        </label>
                    </div>
                </div>
                <button type="submit" disabled id="comfirm" class="btn btn-secondary">Confirmar
                    prova de
                    vida</button>
            </form>
            <div class="spinner-grow align-self-center" hidden style="width: 3rem; height: 3rem;" id="status" role="status">
                <span class="sr-only">Aguarde a confirmação...</span>
            </div>
            @else
            <div class="form-group col-md-12 ">
                <h6 class="font-weight-bold text-secondary">Aguarde pelo mês de
                    {{ date('m', strtotime(session('funcionario')->data_de_nascimento)) }} para realizar a prova de vida</h6>

            </div>
            @endif
        </div>

        @else
        <div class="col-8 col-md-4 mycontent-right" style="padding-left: 1%; margin-top: 5%">
            <div class="card border-danger mb-3">
                <div class="card-header text-danger">Funcionário não encontrado</div>
            </div>
        </div>

        @endif
        @endif
        {{-- @endisset  --}}
    </div>
</div>
@endsection
<script>
    var click = document.getElementById('comfirm');
    var status = document.getElementById('status');
    var checkbox = document.getElementById('is_confirmed');
    function isConfirmed(){

        var click = document.getElementById('comfirm');
            var status = document.getElementById('status');
            var checkbox = document.getElementById('is_confirmed');
            if (checkbox.checked == true){
                checkbox.value = true
                click.disabled=false
                click.className = "btn btn-primary";
            }else{
                checkbox.value = false
                click.disabled=true
                click.className = "btn btn-secondary";
            }
    }

    function confirm(){
        var click = document.getElementById('comfirm');
        var status = document.getElementById('status');
        click.disabled=true
        status.hidden = false

        var check = document.getElementById('is_confirmed');
        var isConfirmed = check.value;
        $.ajax({
        /* the route pointing to the post function */
        url: '/prova',
        method: 'POST',
        /* send the csrf-token and the input to the controller */
        type: "POST",
        data: {"_token": "{{ csrf_token() }}", is_confirmed: isConfirmed},
        dataType: 'text',
        /* remind that 'data' is the response of the AjaxController */
            success: function (response) {
                status.hidden = true
                console.log(response)
            },
            error: function(XMLHttpRequest, textStatus, errorThrown){
                status.hidden = true
                console.log("erro  "+textStatus);
            }
        });
    }

    function visibleCell() {
        var telefone = document.getElementById('telefone');
        telefone.disabled = false;
    }
</script>